export default {
  year: "",
  enrollmentFee: "",
  presentationVideoUrl: "",
  startDate: "",
  endDate: "",
  extensionDate: "",
  allowRegistration: true,
  testerEmails: [],
  resultPublicationDate: "",
  resultPublicationDateExternal: "",
  roomNoticeEmailDate: "",
  resultUrl: "",
  description: "",
  testDate: "",
  nextEnrollmentNumber: 1001,
};
